### ISSUE TITLE
Submitting PRs

### ISSUE THREAD

**Issue by fatmali** [DevCEldoret/devceldoret-backend#1]
Hi @miami78,

Great stuff! I like how the repo is looking. However I'd like to encourage you to do pull requests and requesting for code reviews instead of committing directly to master. This gives a chance for people to know what you have done and review it before it is merged in. It will also help you learn and teach a lot from the code reviews. This is part of the process that we need to establish and discuss in the call but I felt the need to create an issue as you continue working. Take a look at some open source projects, can come up with a mininimal contribution.md and we can discuss from there.

**Comment by miami78** [comment]
@fatmali i thought about it,the last changes i made was for the final project structure,i had missed something that i wanted layed out.from here we can discuss the project scope and what needs to be implemented,start creating issues,guys can do PRs to the development branch and wait for it to be reviewed
